config/routes.rb
Qawiki::Application.routes.draw do
  resources :revisions

  resources :users

  resources :pages

  
  root :to => 'pages#index'



  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :setup_steps, :test_strategy, :title

  has_many :revisions

  validates :title, :presence => true,
  					:length => { :minimum => 5 }
end

app/models/revision.rb
class Revision < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :content, :page_id

  belongs_to :page
  belongs_to :user

  def parsed_contents
    contents = self.contents.gsub(/(\w*_\w*)/) {|match| "<a href='#{match.downcase}'>#{match.gsub('_', ' ')}</a>"}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password

  has_many :revisions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    #@page = Page.find(params[:id])
    @page = Page.find_or_create_by_title(params[:title])
    return redirect_to edit_page_path(:title => @page.title) if @page.revisions.empty?

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
    @revision = @page.revisions.last || Revision.new
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  # GET /revisions
  # GET /revisions.json
  def index
    @revisions = Revision.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @revisions }
    end
  end

  # GET /revisions/1
  # GET /revisions/1.json
  def show
    @revision = Revision.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @revision }
    end
  end

  # GET /revisions/new
  # GET /revisions/new.json
  def new
    @revision = Revision.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @revision }
    end
  end

  # GET /revisions/1/edit
  def edit
    #@revision = Revision.find(params[:id])
    @page = Page.find_by_title(params[:title])
  end

  # POST /revisions
  # POST /revisions.json
  def create
    @revision = Revision.new(params[:revision])

    respond_to do |format|
      if @revision.save
        #format.html { redirect_to @revision, notice: 'Revision was successfully created.' }
        format.html { redirect_to page_base_url(:page_title => @revision.page.title) }
        format.json { render json: @revision, status: :created, location: @revision }
      else
        #format.html { render action: "new" }
        format.html { redirect_to page_base_url(:page_title => @revision.page.title) }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /revisions/1
  # PUT /revisions/1.json
  def update
    @revision = Revision.find(params[:id])

    respond_to do |format|
      if @revision.update_attributes(params[:revision])
        format.html { redirect_to @revision, notice: 'Revision was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revisions/1
  # DELETE /revisions/1.json
  def destroy
    @revision = Revision.find(params[:id])
    @revision.destroy

    respond_to do |format|
      format.html { redirect_to revisions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qawiki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #EEEEEE;">

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :test_strategy %><br />
    <%= f.text_area :test_strategy %>
  </div>
  <div class="field">
    <%= f.label :setup_steps %><br />
    <%= f.text_area :setup_steps %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Test strategy</th>
    <th>Setup steps</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.test_strategy %></td>
    <td><%= page.setup_steps %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @page.revisions.last.contents %>
</p>
<p>
  last edited by 
  <%= @page.revisions.last.users.name %> 
  on 
  <%= time_ago_in_words(@page.revisions.last.created_at) %> 
  ago
</p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Test strategy:</b>
  <%= @page.test_strategy %>
</p>

<p>
  <b>Setup steps:</b>
  <%= @page.setup_steps %>
</p>


<%= #link_to 'Edit', edit_page_path(@page) 
    link_to 'Edit', page_edit_url(:title => @page.title) 
%> |
<%= link_to 'Back', pages_path %>

app/views/revisions/_form.html.erb
<%= form_for(@revision) do |f| %>
  <% if @revision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@revision.errors.count, "error") %> prohibited this revision from being saved:</h2>

      <ul>
      <% @revision.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_area :content %>
  <%= f.hidden_field :page_id, :value => @page_id %>
  
  <% fields_for :user do |u| %>
    Your Name
    <%= u.text_field :name %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/revisions/edit.html.erb
<h1>Editing revision</h1>

<%= render 'form' %>

<%= link_to 'Show', @revision %> |
<%= link_to 'Back', revisions_path %>

app/views/revisions/index.html.erb
<h1>Listing revisions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @revisions.each do |revision| %>
  <tr>
    <td><%= link_to 'Show', revision %></td>
    <td><%= link_to 'Edit', edit_revision_path(revision) %></td>
    <td><%= link_to 'Destroy', revision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Revision', new_revision_path %>

app/views/revisions/new.html.erb
<h1>New revision</h1>

<%= render 'form' %>

<%= link_to 'Back', revisions_path %>

app/views/revisions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_revision_path(@revision) %> |
<%= link_to 'Back', revisions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>